name: pymc_env
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.4.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arviz=0.15.1
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.14.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=2.120
  - blas-devel=3.9.0
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.4.0
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - cons=0.4.6
  - contourpy=1.2.1
  - cycler=0.12.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - etuples=0.3.9
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fastprogress=1.0.3
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - getopt-win32=0.1
  - glib=2.80.3
  - glib-tools=2.80.3
  - graphite2=1.3.13
  - graphviz=8.1.0
  - gst-plugins-base=1.24.6
  - gstreamer=1.24.6
  - gts=0.7.6
  - h2=4.1.0
  - h5netcdf=1.3.0
  - h5py=3.11.0
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - importlib_resources=6.4.0
  - intel-openmp=2023.2.0
  - ipykernel=6.29.5
  - ipympl=0.9.3
  - ipython=8.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.0.13
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.11
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=18.1.8
  - libcurl=8.9.1
  - libdeflate=1.21
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgd=2.3.3
  - libglib=2.80.3
  - libhwloc=2.11.1
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libogg=1.3.5
  - libpng=1.6.43
  - libpython=2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvmlite=0.42.0
  - logical-unification=0.4.6
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-toolchain_win-64=2.5.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - markupsafe=2.1.5
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.7
  - minikanren=1.0.3
  - mistune=3.0.2
  - mkl=2023.2.0
  - mkl-devel=2023.2.0
  - mkl-include=2023.2.0
  - mkl-service=2.4.1
  - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.0.6
  - notebook-shim=0.2.4
  - numba=0.59.0
  - numpy=1.24.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.1.2
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=23.2.1
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - ply=3.11
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pymc=5.8.0
  - pymc-base=5.8.0
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytensor=2.15.0
  - pytensor-base=2.15.0
  - python=3.11.6
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-graphviz=0.20.3
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=306
  - pywinpty=2.0.13
  - pyyaml=6.0.2
  - pyzmq=26.1.0
  - qt-main=5.15.8
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - scipy=1.11.3
  - seaborn=0.13.2
  - send2trash=1.8.3
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - tbb=2021.12.0
  - terminado=0.18.1
  - tinycss2=1.3.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.2.2
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - watermark=2.4.3
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.11
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xarray=2023.10.1
  - xarray-einstats=0.7.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.0
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - polars==1.5.0
